### PR TITLE
Add rounded corners

### PR DESCRIPTION
**Pull request by ghost**
Work in progress.  Attempting to address #9.  Stole some ideas from https://github.com/mdwheele/owls/pull/11/commits/3e82e9df7eb53aa9ef35c564be07f883dbf8df93

This looks absolutely disgusting on Ubuntu 20.04 but quite nice on Windows 10.

`Gander.setGood(!Goose.isGood(this))`

### CODE REVIEW

**Comment by ghost** [comment]
@mdwheele This is looking pretty good to me.  I was able to test on Windows 10 and Xubuntu 18.04.  Not able to test on macOS at the moment, but can do that later if desired.  When you have time, please take a look!

### Windows 10
---
owls-windows-10

### Xubuntu 18.04
---
owls-xubuntu-18 04

**Comment by ghost** [comment]
### macOS 10.15.7
---
owls-macos

**Comment by mdwheele** [comment]
Oh man, so much rounded. It's amazing. This looks great to me.

Does the MacOS shadow look much darker? I bet they're putting a shadow on the native window so that when we add our own, it doubles up. Could you see how disabling shadow on `BrowserWindow` affects things? We're never going to get pixel-perfect likeness everywhere, but worth a shot to get close.

**Comment by ghost** [comment]
Sure!  Here it is with `hasShadow: false` on macOS.  Looks like the others now.  I will commit this.

---
owls-macos-lighter

**Comment by ghost** [comment]
@mdwheele Just noting this is ready for review whenever you have time.  Thanks!

**Pull request closed without merging**
